### ISSUE TITLE
Time comparison between K-means and improvised K-means

### ISSUE THREAD

**Issue by hafeezali** [rahul-kumi/DAA-K-means-improvisation#1]
We need to have a bar chart or something, which would serve as a time comparison between the algorithms.

I guess keeping three separate codes would be good,
the first one with absolutely no improvements,
the second one with the improvement given in the paper: updating the new centroids, and
the third one with the improvement put forth from us: improving the selection of the initial centroids

**Comment by rahul-kumi** [comment]
@hafeezali, sure thing, but I think I will have to scale the timing count, as its bare perceivable.....
